name: Release API

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  changed_files:
    runs-on: ubuntu-latest # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      # -----------------------------------------------------------------------------------------------------------
      # Example 1
      # -----------------------------------------------------------------------------------------------------------
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files_yaml: |
            api:
              - api/**
              - package.json
              - package-lock.json
              - .releaserc.json
              - Dockerfile
              - .dockerignore
              - .babelrc
              - jest.config.js
              - jest.setup.js

      - name: Check if any files were changed
        if: steps.changed-files.outputs.api_any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.api_all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
