name: Release API

on:
  workflow_run:
    workflows: ["Testing Pipeline"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ls files
        run: ls -la

      - name: Verify API changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        with:
          files: |
            api/**
            package.json
            package-lock.json
            .releaserc.json
            Dockerfile
            .dockerignore
            .babelrc
            jest.config.js
            jest.setup.js

      - name: Semantic release (API)
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
